name: flowcheck install dependencies & run code checkers
description: Install dependencies, run code checkers & run linter on creating and updating a Pull request.
branding:
  icon: 'check-circle'
  color: 'green'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      shell: bash

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      shell: bash
      with:
        php-version: '8.1'

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@v2
      shell: bash
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm ci
      shell: bash

    - name: Run tests
      run: composer run test
      shell: bash

    - name: Run linter
      run: npm run lint
      shell: bash